In [7]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

# Census API Key
#from apikeys import CENSUS_API_KEY
c = Census('90c48972753ebda53bd3bb1643aa673ac0ce728f', year=2016)

In [8]:
# Run Census Search to retrieve data on all zip codes (2013 ACS5 Census)
# See: https://github.com/CommerceDataService/census-wrapper for library documentation
# See: https://gist.github.com/afhaque/60558290d6efd892351c4b64e5c01e9b for labels
census_data = c.acs5.get(("NAME", "B19013_001E", "B19301_001E",
                            "B23025_004E", "B23025_005E", "B17001_002E",
                            "B17001_003E","B17001_017E","B17001A_002E",
                            "B17001B_002E","B02001_004E","B17001D_002E",
                            "B17001E_002E","B17001G_002E","B17001I_002E",
                            "B17012_002E","B17012_003E","B17012_009E",
                            "B17012_014E","B01002_001E","B01002_002E",
                            "B01002_003E","B01003_001E","B25077_001E",
                            "B25088_002E","B15003_002E","B15003_017E",
                            "B15003_018E","B15003_021E","B15003_022E",
                            "B15003_023E","B15003_024E","B15003_025E",
                         ),
                         {'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_df = pd.DataFrame(census_data)

# Column Reordering
census_df = census_df.rename(columns={
    "B19013_001E": "income",
    "B19301_001E": "income_per_capital",
    "B23025_004E": "employment_employed",
    "B23025_005E": "employment_unemployed",
    "B17001_002E": "poverty",
    "B17001_003E": "poverty_male",
    "B17001_017E": "poverty_female",
    "B17001A_002E": "poverty_white_alone",
    "B17001B_002E": "poverty_black_alone",
    "B02001_004E": "population_american_indian_alone",
    "B17001D_002E": "poverty_asian_alone",
    "B17001E_002E": "poverty_native_hawaiian_alone",
    "B17001G_002E": "poverty_two_or_more_races",
    "B17001I_002E": "poverty_hispanic_origin",
    "B17012_002E": "poverty_family",
    "B17012_003E": "poverty_family_married",
    "B17012_009E": "poverty_family_single_male",
    "B17012_014E": "poverty_family_single_female",
    "B01002_001E": "age",
    "B01002_002E": "median_male_age",
    "B01002_003E": "median_female_age",
    "B01003_001E": "population",
    "B25077_001E": "median_home_value",
    "B25088_002E": "median_monthly_owner_costs",
    "B15003_002E": "education_none",
    "B15003_017E": "education_high_school",
    "B15003_018E": "education_ged",
    "B15003_021E": "education_associates",
    "B15003_022E": "education_bachelors",
    "B15003_023E": "education_masters",
    "B15003_024E": "education_professional",
    "B15003_025E": "education_doctorate",
    "zip code tabulation area": "Zipcode"
})

# Add in Poverty Rate (Poverty Count / Population)
#census_pd["Poverty Rate"] = 100 * census_pd["Poverty Count"] / census_pd["Population"]

# Final DataFrame
census_df = census_df[["income", "income_per_capital", 
                       "employment_employed","employment_unemployed",
                       "poverty", "poverty_male",
                       "poverty_female","poverty_white_alone",
                       "poverty_black_alone","population_american_indian_alone",
                       "poverty_asian_alone","poverty_native_hawaiian_alone",
                       "poverty_two_or_more_races","poverty_hispanic_origin",
                       "poverty_family","poverty_family_married",
                       "poverty_family_single_male","poverty_family_single_female",
                       "age","median_male_age",
                       "median_female_age","population",
                       "median_home_value","median_monthly_owner_costs",
                       "education_none","education_high_school",
                       "education_ged","education_associates",
                       "education_bachelors","education_masters",
                       "education_professional","education_doctorate",
                       "Zipcode"
                    ]]

# Visualize
print(len(census_df))
census_df.head()

33120

,income,income_per_capital,employment_employed,employment_unemployed,poverty,poverty_male,poverty_female,poverty_white_alone,poverty_black_alone,population_american_indian_alone,...,median_monthly_owner_costs,education_none,education_high_school,education_ged,education_associates,education_bachelors,education_masters,education_professional,education_doctorate,Zipcode
0,56714.0,30430.0,8715.0,479.0,1462.0,549.0,913.0,1221.0,15.0,5.0,...,1489.0,69.0,3624.0,283.0,1342.0,2016.0,1353.0,121.0,116.0,01001
1,48923.0,26072.0,15180.0,1271.0,8351.0,4229.0,4122.0,6441.0,842.0,140.0,...,2146.0,212.0,1540.0,138.0,694.0,3161.0,2956.0,592.0,2040.0,01002
2,2499.0,3829.0,4258.0,1021.0,54.0,2.0,52.0,15.0,31.0,30.0,...,-666666666.0,0.0,0.0,7.0,0.0,3.0,10.0,1.0,1.0,01003
3,70568.0,32169.0,2835.0,153.0,230.0,90.0,140.0,230.0,0.0,0.0,...,1645.0,0.0,1292.0,120.0,321.0,505.0,327.0,92.0,76.0,01005
4,80502.0,36359.0,8050.0,543.0,1410.0,607.0,803.0,1229.0,35.0,0.0,...,1768.0,18.0,1946.0,305.0,978.0,2185.0,1455.0,228.0,387.0,01007

In [4]:
census_df.to_csv("census_raw.csv", encoding="utf-8", index=False)